<?php $order = $block->getOrder();
if($order->getId()){
$additionalInformation = $order->getPayment()->getAdditionalInformation();
$method = $order->getPayment()->getMethod();
 ?>
  <h1><?= __("Order #".$block->getOrder()->getIncrementId()); ?></h1>
 <div class="order-date">
    <h2><?= /* @escapeNotVerified */ __('%1', '<date>' . $block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG) . '</date>') ?></h2>
</div>
<div class="knawat-block block-order-details-view">
    <div class="knawat-block-title">
        <strong><h3><?= /* @escapeNotVerified */ __('Order Information') ?></h3></strong>
    </div>
    <div class="block-content">
    <?php if (!$order->getIsVirtual()): ?>
        <div class="box-knawat box-order-shipping-address">
            <strong class="box-title"><span><?= /* @escapeNotVerified */ __('Shipping Address') ?></span></strong>
            <div class="box-content">
                <address><?= /* @escapeNotVerified */ $block->getFormattedAddress($order->getShippingAddress()) ?></address>
            </div>
        </div>

        <div class="box-knawat box-order-shipping-method">
            <strong class="box-title">
                <span><?= /* @escapeNotVerified */ __('Shipping Method') ?></span>
            </strong>
            <div class="box-content">
            <?php if ($order->getShippingDescription()): ?>
                <?= $block->escapeHtml($order->getShippingDescription()) ?>
            <?php else: ?>
                <?= /* @escapeNotVerified */ __('No shipping information available') ?>
            <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>

        <div class="box-knawat box-order-billing-address">
            <strong class="box-title">
                <span><?= /* @escapeNotVerified */ __('Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address><?= /* @escapeNotVerified */ $block->getFormattedAddress($order->getBillingAddress()) ?></address>
            </div>
        </div>
        <div class="box-knawat box-order-billing-method">
            <strong class="box-title">
                <span><?= /* @escapeNotVerified */ __('Payment Method') ?></span>
            </strong>
            <div class="box-content">
                <?php if (($method != '') && array_key_exists('method_title', $additionalInformation)) { ?>
                    <dt class="title"><?php echo $additionalInformation['method_title']; ?></dt>
                <?php } ?>     
            </div>
        </div>
    </div>
</div>
 <div class="order-details-items invoice">
<?php foreach ($order->getInvoiceCollection() as $_invoice): ?>
<div class="order-title">
    <strong><?= /* @escapeNotVerified */ __('Invoice #') ?><?= /* @escapeNotVerified */ $_invoice->getIncrementId() ?></strong>
</div>
<div class="table-wrapper table-order-items invoice">
    <table class="data table table-order-items invoice" id="my-invoice-table-<?= /* @escapeNotVerified */ $_invoice->getId() ?>">
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Items Invoiced') ?></caption>
        <thead>
            <tr>
                <th class="col name"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
                <th class="col sku"><?= /* @escapeNotVerified */ __('SKU') ?></th>
                <th class="col price"><?= /* @escapeNotVerified */ __('Price') ?></th>
                <th class="col qty"><?= /* @escapeNotVerified */ __('Qty Invoiced') ?></th>
                <th class="col subtotal"><?= /* @escapeNotVerified */ __('Subtotal') ?></th>
            </tr>
        </thead>
        <?php $_items = $_invoice->getAllItems(); ?>
        <?php foreach ($_items as $_item): ?>
            <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot>
            <?= $block->getInvoiceTotalsHtml($_invoice) ?>
        </tfoot>
    </table>
</div>
<?= $block->getInvoiceCommentsHtml($_invoice) ?>
<?php endforeach; ?>
</div>
<?php } ?>
