<?php $_product = $block->getProduct(); 
$sku = $_product->getSku();
$is_Knawat = $_product->getIsKnawat();

if($sku && $is_Knawat){
	?>
	<script>
		require(['jquery'],function(){
			jQuery( document ).ready(function(){
				setTimeout(function() {
					var url = "<?php echo $this->getUrl('dropshipping/manage/viewknawatproduct') ?>";
					jQuery.ajax({
						url: url,
						type: "POST",
						data: {form_key:window.FORM_KEY,sku:"<?php echo $sku; ?>"},
						cache: false,
						success: function(response){
						},
					});
				}, 18000);
			});
		});
	</script>
	<?php } ?>