<?php
$_item = $block->getItem();
$order = $block->getOrder();
?>
<tr id="order-item-row-<?= /* @escapeNotVerified */ $_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
            <?php if (!$block->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                <dd>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                    <?php else: ?>
                        <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd>
                    <?= nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                </dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtml(__('SKU')) ?>"><?= /* @escapeNotVerified */ $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <ul class="items-qty">
        <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
            <li class="item">
                <span class="title"><?= /* @escapeNotVerified */ __('Ordered') ?></span>
                <span class="content"><?= /* @escapeNotVerified */ $block->getItem()->getQtyOrdered()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyShipped() > 0): ?>
            <li class="item">
                <span class="title"><?= /* @escapeNotVerified */ __('Shipped') ?></span>
                <span class="content"><?= /* @escapeNotVerified */ $block->getItem()->getQtyShipped()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
            <li class="item">
                <span class="title"><?= /* @escapeNotVerified */ __('Canceled') ?></span>
                <span class="content"><?= /* @escapeNotVerified */ $block->getItem()->getQtyCanceled()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
            <li class="item">
                <span class="title"><?= /* @escapeNotVerified */ __('Refunded') ?></span>
                <span class="content"><?= /* @escapeNotVerified */ $block->getItem()->getQtyRefunded()*1 ?></span>
            </li>
        <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
     <?php 
     if($block->getSalesController() == 'orderviewsales'){
        if($block->getCheckKnawatItems()){
            if(($order->getKnawatOrderStatus()) || ($order->getShipmentProviderName()) || ($order->getShipmentTrackingNumber()) ){ 
                $itemSku = $block->getItem()->getSku();
                $isKnawat = $block->checkIsKnawat($itemSku);
                    if(($order->getShipmentProviderName()) && ($order->getShipmentTrackingNumber())) {
                        $provider = $order->getShipmentProviderName();
                        $trackingNumber = $order->getShipmentTrackingNumber();
                        $trackLink = $block->getTracking($provider,$trackingNumber);
                    }
                if($isKnawat){
                ?>
         <td class="col knawat" data-th="<?= $block->escapeHtml(__('Knawat')) ?>">
            <ul class="items-qty">
            <?php if($order->getKnawatOrderStatus()){ ?>
                <li class="item">
                <span class="title"><b><?= /* @escapeNotVerified */ __('Status') ?></b></span>
                <span class="content"><?= /* @escapeNotVerified */ $order->getKnawatOrderStatus() ?></span>
            </li>
            <?php } ?>
            <?php if($order->getShipmentProviderName()){ ?>
                <li class="item">
                <span class="title"><b><?= /* @escapeNotVerified */ __('Shipment Provider') ?></b></span>
                <span class="content"><?= /* @escapeNotVerified */ $order->getShipmentProviderName() ?></span>
            </li>
            <?php } ?>
            <?php if($order->getShipmentTrackingNumber()){ ?>
                <li class="item">
                <span class="title"><b><?= /* @escapeNotVerified */ __('Tracking Number') ?></b></span>
                <span class="content"><?= /* @escapeNotVerified */ $order->getShipmentTrackingNumber() ?></span>
                 <?php if(isset($trackLink)){ ?>
             <span class="actions"><a href="<?php echo $trackLink; ?>" target="_blank"><?= $block->escapeHtml(__('Track')) ?></a></span>
          <?php } ?>
            </li>
            <?php } ?>
        </ul>
         </td>               
    <?php } 
        }
    }
}
    ?>
</tr>
