<script>
    require(['jquery'],function(){
        jQuery( document ).ready(function(){
            setTimeout(function() {
                var url = "<?php echo $this->getUrl('dropshipping/dropshipping/pullorder') ?>";
                jQuery.ajax({
                    url: url,
                    type: "POST",
                    data: {form_key:window.FORM_KEY},
                    cache: false,
                    success: function(response){
                    },
                });
            }, 18000);
        });
    });
</script>