<?php  $connection = $block->getKnawatConnection(); 
       $importStatus = $block->getImportStatus();  
       if($block->isVersionTwo()){
        $knawatLabel = 'knawat-label-2';
       }else{
        $knawatLabel = 'knawat-label';
       }  
?>
<div class="admin__scope-old">
    <fieldset class="fieldset admin__fieldset">
        <legend class="admin__legend legend">
            <span><?php echo __('Product Import') ?></span>
        </legend>
        <p><?php echo __('Plugin auto import/update products from knawat.com in background on regular interval. But, if you want then you can manually start import.') ?></p>
        <br/><!-- Spaces are good :) -->
        <form class="form" action="<?php echo $this->getUrl("dropshipping/dropshipping/saveimport") ?>" method="post" name="import_form">
            <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
            <div class="field knawat-admin-control">
                <label for="start_stop_import" class="<?php echo $knawatLabel; ?>">
                    <span class="knawat-admin-label"><strong><?php echo __('Start product import') ?></strong></span>
                </label>
                <button type="submit" class="action submit primary input-text" title="<?php echo __('Start Import') ?>" <?php if (!$connection || $importStatus ) {  echo "disabled"; }?>>
                    <span><?php echo __('Start Import') ?></span>
                </button>

                <?php if ($block->getImportStatus()) : ?>
                    <input name="operation" type="hidden" value="stop_import" />
                    <button type="submit" class="action submit input-text" title="<?php echo __('Stop Import') ?>" onclick="return confirm('<?php echo __('Are you sure? do you really want to stop import?') ?>');">
                        <span><?php echo __('Stop Import') ?></span>
                    </button>
                <?php endif; ?>

                <?php
                if ($block->getImportStatus()) {
                    $importData = $block->getImportStatus();
                    $imported = $failed = $updated = $skipped = 0;
                    if (array_key_exists('imported', $importData)) {
                        $imported = $importData['imported'];
                    }
                    if (array_key_exists('failed', $importData)) {
                        $failed = $importData['failed'];
                    }
                    if (array_key_exists('updated', $importData)) {
                        $updated = $importData['updated'];
                    }
                    if (array_key_exists('skipped', $importData)) {
                        $skipped = $importData['skipped'];
                    } ?>
                    <div class="knawat-admin-control">
                        <label for="start_stop_import" class="<?php echo $knawatLabel; ?>">
                            <span class="knawat-admin-label"></span>
                        </label>
                        <span><i><?php echo __("Product import is in-progress already. you can't start import now. Please find current import status below."); ?></i></span>
                    </div>
                    <?php if (isset($imported)) : ?>
                        <div class="knawat-admin-control">
                        <label for="start_stop_import" class="<?php echo $knawatLabel; ?>">
                            <span class="knawat-admin-label"></span>
                        </label>
                        <span><strong><?php echo __("Imported : "); ?></strong></span>
                        <?php echo $imported. ' ' . __("Products");
                    endif; ?>
                    </div>
                    <?php if (isset($updated)) : ?>
                        <div class="knawat-admin-control">
                        <label for="start_stop_import" class="<?php echo $knawatLabel; ?>">
                            <span class="knawat-admin-label"></span>
                        </label>
                        <span><strong><?php echo __("Updated : "); ?></strong></span>
                        <?php echo $updated. ' ' . __("Products");
                    endif; ?>
                    </div>
                    <?php if (isset($skipped)) : ?>
                        <div class="knawat-admin-control">
                        <label for="start_stop_import" class="<?php echo $knawatLabel; ?>">
                            <span class="knawat-admin-label"></span>
                        </label>
                        <span><strong><?php echo __("Skipped : "); ?></strong></span>
                        <?php echo $skipped. ' ' . __("Products");
                    endif; ?>
                    </div>
                    <?php if (isset($failed)) : ?>
                        <div class="knawat-admin-control">
                        <label for="start_stop_import" class="<?php echo $knawatLabel; ?>">
                            <span class="knawat-admin-label"></span>
                        </label>
                        <span><strong><?php echo __("Failed : "); ?></strong></span>
                        <?php echo $failed. ' ' . __("Products");
                    endif; ?>
                    </div>
                <?php }
                ?>
            </div>
            <?php if(!$connection){ ?>
            <div class="field knawat-admin-control">
                <label for="start_stop_import" class="<?php echo $knawatLabel; ?>">
                    <span class="knawat-admin-label"></span>
                </label>
                <span><?php echo __("You're not connected to ") ?><a href="https://knawat.com/" target="_blank"><?php echo __("knawat.com "); ?></a><?php echo __(", please make a connection for start import."); ?></span>
            </div>
            <?php } ?>
        </form>
    </fieldset>
</div>
